import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "/src/theme/globals.css";
import { cn } from "@/infra/cn";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toast/toaster";

export const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "relative flex flex-col min-h-screen bg-background font-sans antialiased list-none",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
